version: "2.4"

services:
  db:
    image: postgres
    volumes:
      - ./${DB_DIR-db-data}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=registry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  registry:
    image: dockerhub/sunbird-rc-core:${RELEASE_VERSION}
    volumes:
      - ./${SCHEMA_DIR-import/schemas}:/home/sunbirdrc/config/public/_schemas
    environment:
      - connectionInfo_uri=jdbc:postgresql://db:5432/registry
      - connectionInfo_username=postgres
      - connectionInfo_password=postgres
      - search_providerName=${SEARCH_PROVIDER_NAME-dev.sunbirdrc.registry.service.NativeSearchService}
      - sunbird_sso_realm=${KEYCLOAK_REALM-sunbird-rc}
      - sunbird_sso_url=http://keycloak:8080/auth
      - sunbird_sso_admin_client_id=${KEYCLOAK_ADMIN_CLIENT_ID-admin-api}
      - sunbird_sso_client_id=${KEYCLOAK_CLIENT_ID-registry-frontend}
      - sunbird_sso_admin_client_secret=${KEYCLOAK_SECRET}
      - signature_enabled=false
      - sunbird_keycloak_user_set_password=true
      - filestorage_connection_url=http://file-storage:9000
      - filestorage_access_key=admin
      - filestorage_secret_key=12345678
      - filestorage_bucket_key=issuance
      - registry_base_apis_enable=false
      - sunbird_keycloak_user_password=abcd@123
      - logging.level.root=INFO
      - enable_external_templates=true
      - async_enabled=${ASYNC_ENABLED-false}
      - authentication_enabled=false
      - manager_type=${MANAGER_TYPE-DefinitionsManager}
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -nv -t1 --spider http://localhost:8081/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 10
  keycloak:
    image: ghcr.io/sunbird-rc/event-engagement-demo/keycloak:latest
    volumes:
      - ./${KEYCLOAK_IMPORT_DIR-import/keycloak}:/opt/jboss/keycloak/imports
      - ./${KEYCLOAK_THEMES_DIR-keycloak/keycloak/themes/nha}:/opt/jboss/keycloak/themes/nha
    environment:
      - KEYCLOAK_LOGO=https://raw.githubusercontent.com/Sunbird-RC/demo-donor-registry/main/imports/header_logo.svg
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_PORT=5432
      - DB_DATABASE=registry
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - KEYCLOAK_USER=${KEYCLOAK_ADMIN_USER-admin}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD-admin}
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/realm-export.json
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_PORTAL_TITLE=
      - KEYCLOAK_PORTAL_SUB_TITLE=
      - SIGN_UP_LINK=/form/signup
      - SHOW_FOOTER=false
      - SHOW_BANNER=false
      - LOGIN_USER_ID_TITLE=Mobile Number
      - MOCK_OTP=true
      - MESSAGE_TEMPLATE=${MESSAGE_TEMPLATE}
      - NOTIFICATION_SERVICE_URL=http://notification-ms:8765/notification-service/v1/notification
      - REGISTER_URL=${REGISTER_URL}
      - INVALID_REGISTRATION=${INVALID_REGISTRATION}
      - INVALID_USERNAME=${INVALID_USERNAME}
      - VALID_OTP=${VALID_OTP}
      - OTP_MAX_RETRY_LIMIT=${OTP_MAX_RETRY_LIMIT}
      - MAX_RETRIES_LIMIT_MESSAGE=${MAX_RETRIES_LIMIT_MESSAGE}
      - MAX_RESEND_TRIES=${MAX_RESEND_TRIES}
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:9990/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: tejashjl/sunbird-rc-donor-portal:${PORTAL_RELEASE_VERSION}
    ports:
      - "80:80"
    depends_on:
      registry:
        condition: service_healthy
      keycloak:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "localhost:80" ]
      interval: 30s
      timeout: 10s
      retries: 10
networks:
  default:
    external:
      name: rcw